 #ifndef CONFIGEMPRESA_GLOBAL_H
#define CONFIGEMPRESA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONFIGEMPRESA_LIBRARY)
#  define CONFIGEMPRESASHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONFIGEMPRESASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONFIGEMPRESA_GLOBAL_H
